module.exports = {
    SELECT_CHAT: 'select-chat',
    NEW_USER_JOIN: 'new-user-join',
    USER_TYPING: 'user-typing',
    NEW_MESSAGE: 'new-message',
    USER_LEAVE_CHAT: 'user-leave-chat',
    UPDATING_USER_AFTER_EXITING_CHAT: 'updating-user-after-exiting-chat',
    USER_OFFLINE: 'user-offline',
    USER_ONLINE: 'user-online',
    ALL_USERS_ONLINE: 'all-users-online',
    USER_REFRESH_AFTER_LEAVE_CHAT: 'user-refresh-after-leave-chat',
    USER_REFRESH_AFTER_JOIN: 'user-refresh-after-join',
    CLIENTS_COUNT_ONLINE_IN_ROOM: 'clients-count-online-in-room',
    USER_DISCONNECT: 'user-disconnect',
}
